// <auto-generated />
using System;
using FifaSquadBuilder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FifaSquadBuilder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904163251_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FifaSquadBuilder.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("Name");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Formations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "4-3-3"
                        },
                        new
                        {
                            Id = 2,
                            Name = "4-4-2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "4-2-3-1"
                        },
                        new
                        {
                            Id = 4,
                            Name = "4-3-2-1"
                        },
                        new
                        {
                            Id = 5,
                            Name = "4-1-2-1-2"
                        },
                        new
                        {
                            Id = 6,
                            Name = "3-5-2"
                        },
                        new
                        {
                            Id = 7,
                            Name = "5-3-2"
                        });
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.FormationPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FormationId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("FormationId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("FormationPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FormationId = 1,
                            OrderIndex = 0,
                            PositionId = 1,
                            X = 50,
                            Y = 5
                        },
                        new
                        {
                            Id = 2,
                            FormationId = 1,
                            OrderIndex = 1,
                            PositionId = 3,
                            X = 15,
                            Y = 20
                        },
                        new
                        {
                            Id = 3,
                            FormationId = 1,
                            OrderIndex = 2,
                            PositionId = 2,
                            X = 35,
                            Y = 18
                        },
                        new
                        {
                            Id = 4,
                            FormationId = 1,
                            OrderIndex = 3,
                            PositionId = 2,
                            X = 65,
                            Y = 18
                        },
                        new
                        {
                            Id = 5,
                            FormationId = 1,
                            OrderIndex = 4,
                            PositionId = 4,
                            X = 85,
                            Y = 20
                        },
                        new
                        {
                            Id = 6,
                            FormationId = 1,
                            OrderIndex = 5,
                            PositionId = 8,
                            X = 30,
                            Y = 50
                        },
                        new
                        {
                            Id = 7,
                            FormationId = 1,
                            OrderIndex = 6,
                            PositionId = 8,
                            X = 50,
                            Y = 45
                        },
                        new
                        {
                            Id = 8,
                            FormationId = 1,
                            OrderIndex = 7,
                            PositionId = 8,
                            X = 70,
                            Y = 50
                        },
                        new
                        {
                            Id = 9,
                            FormationId = 1,
                            OrderIndex = 8,
                            PositionId = 12,
                            X = 20,
                            Y = 80
                        },
                        new
                        {
                            Id = 10,
                            FormationId = 1,
                            OrderIndex = 9,
                            PositionId = 15,
                            X = 50,
                            Y = 85
                        },
                        new
                        {
                            Id = 11,
                            FormationId = 1,
                            OrderIndex = 10,
                            PositionId = 13,
                            X = 80,
                            Y = 80
                        },
                        new
                        {
                            Id = 12,
                            FormationId = 2,
                            OrderIndex = 0,
                            PositionId = 1,
                            X = 50,
                            Y = 5
                        },
                        new
                        {
                            Id = 13,
                            FormationId = 2,
                            OrderIndex = 1,
                            PositionId = 3,
                            X = 15,
                            Y = 20
                        },
                        new
                        {
                            Id = 14,
                            FormationId = 2,
                            OrderIndex = 2,
                            PositionId = 2,
                            X = 35,
                            Y = 18
                        },
                        new
                        {
                            Id = 15,
                            FormationId = 2,
                            OrderIndex = 3,
                            PositionId = 2,
                            X = 65,
                            Y = 18
                        },
                        new
                        {
                            Id = 16,
                            FormationId = 2,
                            OrderIndex = 4,
                            PositionId = 4,
                            X = 85,
                            Y = 20
                        },
                        new
                        {
                            Id = 17,
                            FormationId = 2,
                            OrderIndex = 5,
                            PositionId = 10,
                            X = 15,
                            Y = 55
                        },
                        new
                        {
                            Id = 18,
                            FormationId = 2,
                            OrderIndex = 6,
                            PositionId = 8,
                            X = 40,
                            Y = 50
                        },
                        new
                        {
                            Id = 19,
                            FormationId = 2,
                            OrderIndex = 7,
                            PositionId = 8,
                            X = 60,
                            Y = 50
                        },
                        new
                        {
                            Id = 20,
                            FormationId = 2,
                            OrderIndex = 8,
                            PositionId = 11,
                            X = 85,
                            Y = 55
                        },
                        new
                        {
                            Id = 21,
                            FormationId = 2,
                            OrderIndex = 9,
                            PositionId = 15,
                            X = 35,
                            Y = 85
                        },
                        new
                        {
                            Id = 22,
                            FormationId = 2,
                            OrderIndex = 10,
                            PositionId = 15,
                            X = 65,
                            Y = 85
                        },
                        new
                        {
                            Id = 23,
                            FormationId = 3,
                            OrderIndex = 0,
                            PositionId = 1,
                            X = 50,
                            Y = 5
                        },
                        new
                        {
                            Id = 24,
                            FormationId = 3,
                            OrderIndex = 1,
                            PositionId = 3,
                            X = 15,
                            Y = 20
                        },
                        new
                        {
                            Id = 25,
                            FormationId = 3,
                            OrderIndex = 2,
                            PositionId = 2,
                            X = 35,
                            Y = 18
                        },
                        new
                        {
                            Id = 26,
                            FormationId = 3,
                            OrderIndex = 3,
                            PositionId = 2,
                            X = 65,
                            Y = 18
                        },
                        new
                        {
                            Id = 27,
                            FormationId = 3,
                            OrderIndex = 4,
                            PositionId = 4,
                            X = 85,
                            Y = 20
                        },
                        new
                        {
                            Id = 28,
                            FormationId = 3,
                            OrderIndex = 5,
                            PositionId = 7,
                            X = 35,
                            Y = 38
                        },
                        new
                        {
                            Id = 29,
                            FormationId = 3,
                            OrderIndex = 6,
                            PositionId = 7,
                            X = 65,
                            Y = 38
                        },
                        new
                        {
                            Id = 30,
                            FormationId = 3,
                            OrderIndex = 7,
                            PositionId = 12,
                            X = 20,
                            Y = 65
                        },
                        new
                        {
                            Id = 31,
                            FormationId = 3,
                            OrderIndex = 8,
                            PositionId = 9,
                            X = 50,
                            Y = 68
                        },
                        new
                        {
                            Id = 32,
                            FormationId = 3,
                            OrderIndex = 9,
                            PositionId = 13,
                            X = 80,
                            Y = 65
                        },
                        new
                        {
                            Id = 33,
                            FormationId = 3,
                            OrderIndex = 10,
                            PositionId = 15,
                            X = 50,
                            Y = 88
                        },
                        new
                        {
                            Id = 34,
                            FormationId = 4,
                            OrderIndex = 0,
                            PositionId = 1,
                            X = 50,
                            Y = 5
                        },
                        new
                        {
                            Id = 35,
                            FormationId = 4,
                            OrderIndex = 1,
                            PositionId = 3,
                            X = 15,
                            Y = 20
                        },
                        new
                        {
                            Id = 36,
                            FormationId = 4,
                            OrderIndex = 2,
                            PositionId = 2,
                            X = 35,
                            Y = 18
                        },
                        new
                        {
                            Id = 37,
                            FormationId = 4,
                            OrderIndex = 3,
                            PositionId = 2,
                            X = 65,
                            Y = 18
                        },
                        new
                        {
                            Id = 38,
                            FormationId = 4,
                            OrderIndex = 4,
                            PositionId = 4,
                            X = 85,
                            Y = 20
                        },
                        new
                        {
                            Id = 39,
                            FormationId = 4,
                            OrderIndex = 5,
                            PositionId = 8,
                            X = 30,
                            Y = 45
                        },
                        new
                        {
                            Id = 40,
                            FormationId = 4,
                            OrderIndex = 6,
                            PositionId = 8,
                            X = 50,
                            Y = 42
                        },
                        new
                        {
                            Id = 41,
                            FormationId = 4,
                            OrderIndex = 7,
                            PositionId = 8,
                            X = 70,
                            Y = 45
                        },
                        new
                        {
                            Id = 42,
                            FormationId = 4,
                            OrderIndex = 8,
                            PositionId = 14,
                            X = 35,
                            Y = 70
                        },
                        new
                        {
                            Id = 43,
                            FormationId = 4,
                            OrderIndex = 9,
                            PositionId = 14,
                            X = 65,
                            Y = 70
                        },
                        new
                        {
                            Id = 44,
                            FormationId = 4,
                            OrderIndex = 10,
                            PositionId = 15,
                            X = 50,
                            Y = 88
                        },
                        new
                        {
                            Id = 45,
                            FormationId = 5,
                            OrderIndex = 0,
                            PositionId = 1,
                            X = 50,
                            Y = 5
                        },
                        new
                        {
                            Id = 46,
                            FormationId = 5,
                            OrderIndex = 1,
                            PositionId = 3,
                            X = 15,
                            Y = 20
                        },
                        new
                        {
                            Id = 47,
                            FormationId = 5,
                            OrderIndex = 2,
                            PositionId = 2,
                            X = 35,
                            Y = 18
                        },
                        new
                        {
                            Id = 48,
                            FormationId = 5,
                            OrderIndex = 3,
                            PositionId = 2,
                            X = 65,
                            Y = 18
                        },
                        new
                        {
                            Id = 49,
                            FormationId = 5,
                            OrderIndex = 4,
                            PositionId = 4,
                            X = 85,
                            Y = 20
                        },
                        new
                        {
                            Id = 50,
                            FormationId = 5,
                            OrderIndex = 5,
                            PositionId = 7,
                            X = 50,
                            Y = 38
                        },
                        new
                        {
                            Id = 51,
                            FormationId = 5,
                            OrderIndex = 6,
                            PositionId = 8,
                            X = 30,
                            Y = 55
                        },
                        new
                        {
                            Id = 52,
                            FormationId = 5,
                            OrderIndex = 7,
                            PositionId = 8,
                            X = 70,
                            Y = 55
                        },
                        new
                        {
                            Id = 53,
                            FormationId = 5,
                            OrderIndex = 8,
                            PositionId = 9,
                            X = 50,
                            Y = 70
                        },
                        new
                        {
                            Id = 54,
                            FormationId = 5,
                            OrderIndex = 9,
                            PositionId = 15,
                            X = 35,
                            Y = 88
                        },
                        new
                        {
                            Id = 55,
                            FormationId = 5,
                            OrderIndex = 10,
                            PositionId = 15,
                            X = 65,
                            Y = 88
                        },
                        new
                        {
                            Id = 56,
                            FormationId = 6,
                            OrderIndex = 0,
                            PositionId = 1,
                            X = 50,
                            Y = 5
                        },
                        new
                        {
                            Id = 57,
                            FormationId = 6,
                            OrderIndex = 1,
                            PositionId = 2,
                            X = 25,
                            Y = 18
                        },
                        new
                        {
                            Id = 58,
                            FormationId = 6,
                            OrderIndex = 2,
                            PositionId = 2,
                            X = 50,
                            Y = 15
                        },
                        new
                        {
                            Id = 59,
                            FormationId = 6,
                            OrderIndex = 3,
                            PositionId = 2,
                            X = 75,
                            Y = 18
                        },
                        new
                        {
                            Id = 60,
                            FormationId = 6,
                            OrderIndex = 4,
                            PositionId = 5,
                            X = 10,
                            Y = 45
                        },
                        new
                        {
                            Id = 61,
                            FormationId = 6,
                            OrderIndex = 5,
                            PositionId = 8,
                            X = 35,
                            Y = 50
                        },
                        new
                        {
                            Id = 62,
                            FormationId = 6,
                            OrderIndex = 6,
                            PositionId = 8,
                            X = 50,
                            Y = 45
                        },
                        new
                        {
                            Id = 63,
                            FormationId = 6,
                            OrderIndex = 7,
                            PositionId = 8,
                            X = 65,
                            Y = 50
                        },
                        new
                        {
                            Id = 64,
                            FormationId = 6,
                            OrderIndex = 8,
                            PositionId = 6,
                            X = 90,
                            Y = 45
                        },
                        new
                        {
                            Id = 65,
                            FormationId = 6,
                            OrderIndex = 9,
                            PositionId = 15,
                            X = 35,
                            Y = 85
                        },
                        new
                        {
                            Id = 66,
                            FormationId = 6,
                            OrderIndex = 10,
                            PositionId = 15,
                            X = 65,
                            Y = 85
                        },
                        new
                        {
                            Id = 67,
                            FormationId = 7,
                            OrderIndex = 0,
                            PositionId = 1,
                            X = 50,
                            Y = 5
                        },
                        new
                        {
                            Id = 68,
                            FormationId = 7,
                            OrderIndex = 1,
                            PositionId = 5,
                            X = 10,
                            Y = 25
                        },
                        new
                        {
                            Id = 69,
                            FormationId = 7,
                            OrderIndex = 2,
                            PositionId = 2,
                            X = 30,
                            Y = 18
                        },
                        new
                        {
                            Id = 70,
                            FormationId = 7,
                            OrderIndex = 3,
                            PositionId = 2,
                            X = 50,
                            Y = 15
                        },
                        new
                        {
                            Id = 71,
                            FormationId = 7,
                            OrderIndex = 4,
                            PositionId = 2,
                            X = 70,
                            Y = 18
                        },
                        new
                        {
                            Id = 72,
                            FormationId = 7,
                            OrderIndex = 5,
                            PositionId = 6,
                            X = 90,
                            Y = 25
                        },
                        new
                        {
                            Id = 73,
                            FormationId = 7,
                            OrderIndex = 6,
                            PositionId = 8,
                            X = 30,
                            Y = 50
                        },
                        new
                        {
                            Id = 74,
                            FormationId = 7,
                            OrderIndex = 7,
                            PositionId = 8,
                            X = 50,
                            Y = 45
                        },
                        new
                        {
                            Id = 75,
                            FormationId = 7,
                            OrderIndex = 8,
                            PositionId = 8,
                            X = 70,
                            Y = 50
                        },
                        new
                        {
                            Id = 76,
                            FormationId = 7,
                            OrderIndex = 9,
                            PositionId = 15,
                            X = 35,
                            Y = 85
                        },
                        new
                        {
                            Id = 77,
                            FormationId = 7,
                            OrderIndex = 10,
                            PositionId = 15,
                            X = 65,
                            Y = 85
                        });
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("SourceLeagueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SourceLeagueId")
                        .IsUnique();

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Nation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("NationId")
                        .HasColumnType("int");

                    b.Property<int>("Overall")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("Potential")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValueEUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WageEUR")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("Name");

                    b.HasIndex("NationId");

                    b.HasIndex("Overall");

                    b.HasIndex("PositionId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GK",
                            Name = "Goalkeeper"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CB",
                            Name = "Centre Back"
                        },
                        new
                        {
                            Id = 3,
                            Code = "LB",
                            Name = "Left Back"
                        },
                        new
                        {
                            Id = 4,
                            Code = "RB",
                            Name = "Right Back"
                        },
                        new
                        {
                            Id = 5,
                            Code = "LWB",
                            Name = "Left Wing Back"
                        },
                        new
                        {
                            Id = 6,
                            Code = "RWB",
                            Name = "Right Wing Back"
                        },
                        new
                        {
                            Id = 7,
                            Code = "CDM",
                            Name = "Central Defensive Midfielder"
                        },
                        new
                        {
                            Id = 8,
                            Code = "CM",
                            Name = "Central Midfielder"
                        },
                        new
                        {
                            Id = 9,
                            Code = "CAM",
                            Name = "Central Attacking Midfielder"
                        },
                        new
                        {
                            Id = 10,
                            Code = "LM",
                            Name = "Left Midfielder"
                        },
                        new
                        {
                            Id = 11,
                            Code = "RM",
                            Name = "Right Midfielder"
                        },
                        new
                        {
                            Id = 12,
                            Code = "LW",
                            Name = "Left Winger"
                        },
                        new
                        {
                            Id = 13,
                            Code = "RW",
                            Name = "Right Winger"
                        },
                        new
                        {
                            Id = 14,
                            Code = "CF",
                            Name = "Centre Forward"
                        },
                        new
                        {
                            Id = 15,
                            Code = "ST",
                            Name = "Striker"
                        });
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Squad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FormationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("WageBudgetEUR")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.HasIndex("UserId");

                    b.ToTable("Squads");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.SquadPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FormationPositionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsStartingXI")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SlotOrder")
                        .HasColumnType("int");

                    b.Property<int>("SquadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormationPositionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SquadId", "FormationPositionId")
                        .IsUnique();

                    b.HasIndex("SquadId", "PlayerId")
                        .IsUnique();

                    b.ToTable("SquadPlayers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8f14e45f-ceea-467e-9575-e5c1d1e12a10",
                            ConcurrencyStamp = "8f14e45f-ceea-467e-9575-e5c1d1e12a10",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "3c59dc04-8bf5-4c3d-9e79-5ab4e9c4c31b",
                            ConcurrencyStamp = "3c59dc04-8bf5-4c3d-9e79-5ab4e9c4c31b",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Club", b =>
                {
                    b.HasOne("FifaSquadBuilder.Models.League", "League")
                        .WithMany("Clubs")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.FormationPosition", b =>
                {
                    b.HasOne("FifaSquadBuilder.Models.Formation", "Formation")
                        .WithMany("Positions")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FifaSquadBuilder.Models.Position", "Position")
                        .WithMany("FormationPositions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Formation");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Player", b =>
                {
                    b.HasOne("FifaSquadBuilder.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FifaSquadBuilder.Models.Nation", "Nation")
                        .WithMany("Players")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FifaSquadBuilder.Models.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Nation");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Squad", b =>
                {
                    b.HasOne("FifaSquadBuilder.Models.Formation", "Formation")
                        .WithMany("Squads")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FifaSquadBuilder.Models.ApplicationUser", "User")
                        .WithMany("Squads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.SquadPlayer", b =>
                {
                    b.HasOne("FifaSquadBuilder.Models.FormationPosition", "FormationPosition")
                        .WithMany("SquadPlayers")
                        .HasForeignKey("FormationPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FifaSquadBuilder.Models.Player", "Player")
                        .WithMany("SquadPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FifaSquadBuilder.Models.Squad", "Squad")
                        .WithMany("SquadPlayers")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormationPosition");

                    b.Navigation("Player");

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FifaSquadBuilder.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FifaSquadBuilder.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FifaSquadBuilder.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FifaSquadBuilder.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.ApplicationUser", b =>
                {
                    b.Navigation("Squads");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Club", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Formation", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("Squads");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.FormationPosition", b =>
                {
                    b.Navigation("SquadPlayers");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.League", b =>
                {
                    b.Navigation("Clubs");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Nation", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Player", b =>
                {
                    b.Navigation("SquadPlayers");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Position", b =>
                {
                    b.Navigation("FormationPositions");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("FifaSquadBuilder.Models.Squad", b =>
                {
                    b.Navigation("SquadPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
